Coffee_shop/coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from coffee_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('menu/', include('goods.urls', namespace='menu')),
    path('user/', include('users.urls', namespace='user')),

    path('__debug__/', include('debug_toolbar.urls')),
    path('basket/', include('baskets.urls', namespace="basket")),
    path('order/', include('orders.urls', namespace="order")),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coffee_shop/coffee_shop/goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    # path('', views.catalog, name='index'),
    path('<slug:category_slug>/', views.catalog, name='catalog'),
    path('search/', views.catalog, name='search'),
    # path('<slug:category_slug>/<int:page>/', views.catalog, name='index'),
    path('dish/<slug:dish_slug>/', views.dish, name='dish'),

    # path('menu/', views.menu, name='menu'),
    # path('', views.menu, name='menu'),
    # path('<slug:category_slug>/', views.menu, name='index'),
    # path('search/', views.menu, name='search'),
]

Coffee_shop/coffee_shop/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('main/', views.main_page, name='main_page'),  
    
]

Coffee_shop/coffee_shop/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-basket/', views.users_basket, name='users-basket'),
    path('logout/', views.logout, name='logout')
]

Coffee_shop/coffee_shop/templates/base.html
{% load static %}

{% load goods_tags  %}
{% load baskets_tags %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon"  href="{% static 'main/img/main-icon.png' %}">

    {% block bootstrap %}
     {% endblock bootstrap %}

    <link rel="stylesheet" href="{% static 'notifications/style/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"> 
   


    
     
     <link rel="stylesheet" href="{% static 'users/style/profile.css' %}"> 

     <link rel="stylesheet" href="{% static 'basket/style/style.css' %}"> 
     <link rel="stylesheet" href="{% static 'orders/style/style.css' %}"> 
    
   
    <link rel="stylesheet" href="{% static 'goods/style/style.css' %}"> 
    <link rel="stylesheet" href="{% static 'main/style/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/style/main.css' %}">
  
    <title>Rofflan</title>


    <!-- это надо -->
  <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>
<!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous"> -->
<script src={% static 'main/js/menu.js' %}></script>
<script src={% static 'main/js/wow.min.js' %}></script>


</head>

{% include "includes/notifications.html"%}
    <!-- HEADER -->
<header class="header">
    <div class="container header__container">
      <h1 class="logo">Rofflan</h1>
  
      <nav class="header__nav">
        <ul>
            <li><a class="home" href="{% url 'main:index' %}">Home</a></li>
            <li><a class="about"href="{% url "menu:catalog" category_slug="all" %}">Меню</a></li>
            
            {% comment %} <li><a class="about"href="#about-us">О нас</a></li> {% endcomment %}

            
            {% if request.path == '/' %}
            <li><a class="about"href="#address">Адрес</a></li>
        {% endif %}
            
            {% if not user.is_authenticated %}  
                </li><a href="{% url "users:login" %}"  class="link-primary">Войти</a></li>
            {% else %}
            <li><a class="about"href="{% url "users:users-basket" %}">Корзина</a></li>
                <li><a class="link-primary" href="{% url "users:profile" %}">Личный кабинет</a></li>
                <li><a class="link-primary" href="{% url "users:logout" %}">Выйти</a></li>
            {% endif %}   
        </ul>
      </nav>
    </div>
  </header>
  
<section>
{% block body %}



{% endblock body %}
</section>   
  

    <footer id="footer" class="footer">
        <div class="footer__desc">
          <div class="container footer__desc-container">
            <div class="footer__about">
              <h4>about Rofflan</h4>
              <p>Чтобы быть в курсе новинок, подписывайтесь на наши социальные сети.</p>
            </div>
            <div class="footer__links">
              <h4>useful links</h4>
              <ul>
                <li><a href="#!">Phasellus gravida semper nisi</a></li>
                <li><a href="#!">Suspendisse nisl elit</a></li>
                <li><a href="#!">Dellentesque habitant morbi</a></li>
                <li><a href="#!">Etiam sollicitudin ipsum</a></li>
              </ul>
            </div>
            <div class="footer__social">
              <h4>social</h4>
              <ul>
                <li>
                  <img src="{% static 'main/img/icon-tw.svg' %}"  alt="twitter">
                  <a href="#!">Twitter</a>
                </li>
                <li>
                  <img src="{% static 'main/img/icon-fb.svg' %}" alt="facebook">
                  <a href="#!">Facebook</a>
                </li>
                <li>
                  <img src="{% static 'main/img/icon-pt.svg' %}" alt="pinterest">
                  <a href="#!">Pinterest</a>
                </li>
                <li>
                  <img src="{% static 'main/img/icon-google.svg' %}" alt="google">
                  <a href="#!">Google</a>
                </li>
                <li>
                  <img src="{% static 'main/img/icon-wb.svg' %}" alt="webflow">
                  <a href="#!">Webflow</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      
        <div class="footer__copy">
          <div class="container">
            <p>Copyright Rofflan with love</p>
          </div>
        </div>
      </footer>
      
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
<!--    <script src="{% static "deps/js/jquery-events.js" %}"></script>-->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>    
<script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src={% static 'notifications/js/script.js' %}></script>

    {% block extra_scripts %}
    <!-- Extra scripts can be included here -->
    {% endblock %}


</html>