Coffee_shop/coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from coffee_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('menu/', include('goods.urls', namespace='menu')),
    path('user/', include('users.urls', namespace='user')),

    path('__debug__/', include('debug_toolbar.urls')),
    path('basket/', include('baskets.urls', namespace="basket")),
    path('order/', include('orders.urls', namespace="order")),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coffee_shop/coffee_shop/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('main/', views.main_page, name='main_page'),  
    
]

Coffee_shop/coffee_shop/orders/urls.py
from django.urls import path 
from  orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

Coffee_shop/coffee_shop/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-basket/', views.users_basket, name='users-basket'),
    path('logout/', views.logout, name='logout')
]

Coffee_shop/coffee_shop/orders/models.py
from django.db import models

from baskets.models import Dishes
from users.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self) -> int:
        return sum(basket.dish_price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)

        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default="В обработке", verbose_name="Статус заказа")

    class Meta:
        db_table="order"
        verbose_name="Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    dish = models.ForeignKey(to=Dishes, on_delete=models.SET_DEFAULT, null=True, verbose_name="Блюдо", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity=models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    objects = OrderItemQuerySet.as_manager()

    def dishes_price(self):
        return round(self.dish.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

Coffee_shop/coffee_shop/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone = models.CharField(max_length=20,
                             validators=[
                                 RegexValidator(
                                     regex=r'^\+7 \(\d{3}\)-\d{3}-\d{4}$',
                                     message="Номер телефона должен быть в формате +7 (000)-000-0000"
                                 )
                             ],
                             unique=True,
                             verbose_name='Телефон'
                             )

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username
        # return f'{self.first_name} {self.last_name} - Телефон: {self.phone}'

Coffee_shop/coffee_shop/users/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm, BaseUserCreationForm, UserCreationForm, UserChangeForm
from users.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
            "phone"
        )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    # username = forms.CharField(
    #     label="Имя",
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': "form-control",
    #                                   'placeholder': 'Введите ваше имя пользователя',
    #                                   }))
    # password = forms.CharField(
    #     label="Пароль",
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'form-control',
    #                                       'placeholder': "Введите ваш пароль"}),
    # )

Coffee_shop/coffee_shop/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect
from users.forms import LoginForm, RegistrationForm, ProfileForm
from django.contrib import auth, messages
from django.urls import reverse
from baskets.templatetags.baskets_tags import user_baskets
from baskets.models import Baskets
from django.db.models import Prefetch
from orders.models import Order, OrderItem


# Create your views here.
def login(request):
    exception = 'Добро пожаловать'
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            session_key = request.session.session_key
            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                if session_key:
                        Baskets.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse("main:index"))
        else:
            exception = "Неправильный логин или пароль"

                
    else:
        form = LoginForm()
    context = {
        'title': 'Home - Авторизация',
        'form': form,
        'exception': exception,
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            session_key = request.session.session_key
            user = form.instance
            auth.login(request, user)
            if session_key:
                Baskets.objects.filter(session_key=session_key).update(user=user)
            messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = RegistrationForm()

    context = {
        'title': 'Home - Регистрация',
        'form_r': form
    }
    return render(request, 'users/login.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("user:profile"))
    else:
        form = ProfileForm(instance=request.user)
    
    orders = Order.objects.filter(user=request.user).prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("dish"),
                )
            ).order_by("-id")


    context = {
        'title': 'Home - Профиль',
        'form': form,
        'orders': orders,
    }
    user_baskets(context, request)
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return HttpResponseRedirect(reverse("main:index"))


def users_basket(request):
    context = {}
    user_baskets(context, request)
    return render(request, 'users/users_basket.html', context)

Coffee_shop/coffee_shop/users/templates/users/login.html
{% load static %}




<link rel="stylesheet" href="{% static 'notifications/style/style.css' %}">
 <link rel="stylesheet" href="{% static 'users/style/login_registration.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

    

    <div class="container" id="container">
        <div class="form-container sign-up-container" >
            <form action="{% url "user:registration" %}" method="post">
                <h1>Регистрация</h1>
                {% csrf_token %}
                <input type="text" class="form-control" id="id_first_name"
                       value="{% if form_r.first_name.value %}{{ form_r.first_name.value }}{% endif %}"
                       name="first_name"
                       placeholder="Введите ваше имя" required>
                    {% if form_r.first_name.errors %}
                    <div class="toast" id="notification-container" >
                        <div class="toast-content">
                             <i class="fas fa-solid fa-check check"></i>
                             <div class="message">
                                 <span class="text text-1">Имя</span>
                                 <span class="text text-2" id="message">{{form_r.first_name.errors}}</span>
                             </div>
                            </div>
                            <i class="fa-solid fa-xmark close"></i>
                        <div class="progress"></div>
                    </div>
                    {% endif %}
                <input type="text" class="form-control" id="id_last_name"
                       value="{% if form_r.last_name.value %}{{ form_r.last_name.value }}{% endif %}"
                       name="last_name"
                       placeholder="Введите вашу фамилию" required>
                    {% if form_r.last_name.errors %}
                    <div class="toast" id="notification-container" >
                        <div class="toast-content">
                             <i class="fas fa-solid fa-check check"></i>
                             <div class="message">
                                 <span class="text text-1">Фамилия</span>
                                 <span class="text text-2" id="message">{{form_r.last_name.errors}}</span>
                             </div>
                            </div>
                            <i class="fa-solid fa-xmark close"></i>
                        <div class="progress"></div>
                    </div>
                    {% endif %}
                <input type="text" class="form-control" id="id_username"
                       value="{% if form_r.username.value %}{{ form_r.username.value }}{% endif %}"
                       name="username"
                       placeholder="Введите ваше имя пользователя" required>
                    {% if form_r.username.errors %}
                        <div class="toast" id="notification-container" >
                            <div class="toast-content">
                                 <i class="fas fa-solid fa-check check"></i>
                                 <div class="message">
                                     <span class="text text-1">Логин</span>
                                     <span class="text text-2" id="message">{{form_r.username.errors}}</span>
                                 </div>
                                </div>
                                <i class="fa-solid fa-xmark close"></i>
                            <div class="progress"></div>
                        </div>
                    {% endif %}
                <input type="email" class="form-control" id="id_email"
                       value="{% if form_r.email.value %}{{ form_r.email.value }}{% endif %}"
                       name="email"
                       placeholder="Введите ваш email" required>
                    {% if form_r.email.errors %}
                    <div class="toast" id="notification-container" >
                        <div class="toast-content">
                             <i class="fas fa-solid fa-check check"></i>
                             <div class="message">
                                 <span class="text text-1">Почта</span>
                                 <span class="text text-2" id="message">{{form_r.email.errors}}</span>
                             </div>
                            </div>
                            <i class="fa-solid fa-xmark close"></i>
                        <div class="progress"></div>
                    </div>
                    {% endif %}
                <input type="text" class="form-control" id="id_phone"
                       value="{% if form_r.phone.value %}{{ form_r.phone.value }}{% endif %}"
                       name="phone"
                       placeholder="Введите телефон" required>
                    {% if form_r.phone.errors %}
                    <div class="toast" id="notification-container" >
                        <div class="toast-content">
                             <i class="fas fa-solid fa-check check"></i>
                             <div class="message">
                                 <span class="text text-1">Телефон</span>
                                 <span class="text text-2" id="message">{{form_r.phone.errors}}</span>
                             </div>
                            </div>
                            <i class="fa-solid fa-xmark close"></i>
                        <div class="progress"></div>
                    </div>
                    {% endif %}
                <input type="password" class="form-control" id="id_password1"
                       value="{% if form_r.password1.value %}{{ form_r.password1.value }}{% endif %}"
                       name="password1"
                       placeholder="Введите пароль" required>
                    {% if form_r.password1.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form_r.password1.errors}}</div>
                    {% endif %}
                <input type="password" class="form-control" id="id_password2"
                       value="{% if form_r.password2.value %}{{ form_r.password2.value }}{% endif %}"
                       name="password2"
                       placeholder="Подтвердите пароль" required>
                    {% if form_r.password2.errors %}
                    <div class="toast" id="notification-container" >
                        <div class="toast-content">
                             <i class="fas fa-solid fa-check check"></i>
                             <div class="message">
                                 <span class="text text-1">Предупреждение</span>
                                 <span class="text text-2" id="message">{{form_r.password2.errors}}</span>
                             </div>
                            </div>
                            <i class="fa-solid fa-xmark close"></i>
                        <div class="progress"></div>
                    </div>
                    {% endif %}
                    
                <button type="submit"> Зарегистрироваться</button>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form action="{% url "user:login" %}" method="post">
                
                <h1>Вход</h1>
                
                <div class="social-container">
                    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>используйте ваш логин и пароль</span>
                {% csrf_token %}
                    {% if request.GET.next %}
                       <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}
                
                    <input type="text" class="form-control"
                           value="{% if form.username.value %}{{form.username.value}}{% endif %}"
                           name="username" id="id_username"
                           placeholder="Введите ваше имя пользователя" required>
                    <input type="password" class="form-control"
                           name="password" id="id_password"
                           placeholder="Введите ваш пароль" required>
                <a href="#"></a>
                <button type="submit">Войти</button>
            </form>
        </div>
        <div class="overlay-container">
            {% if exception %}
                <div class="toast" id="notification-container" >
                    <div class="toast-content">
                        <i class="fas fa-solid fa-check check"></i>
                        <div class="message">
                            <span class="text text-1">Уведомление</span>
                            <span class="text text-2" id="message">{{ exception }}</span>
                        </div>
                    </div>
                    <i class="fa-solid fa-xmark close"></i>
                    <div class="progress"></div>
                </div>
                {% endif %}
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Рады видеть вас снова!</h1>
                    <p>Уже зарегистрированы?</p>
                    <button class="ghost" id="signIn">Войти</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Привет, Друг!</h1>
                    <p>Введи персональные данные и стань нашем гостем </p>
                    <button class="ghost" id="signUp" >Зарегистрироваться</button>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src={% static 'users/js/script.js' %}></script> 
    <script src={% static 'notifications/js/script.js' %}></script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    

Coffee_shop/coffee_shop/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<section style="color: #ccc;" class="order-main" id="basket-main">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="title-basket">Профиль пользователя</h3>
                    <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="profile">
                            <div >
                                {% if user.image %}
                                <img src="{{user.image.url}}"
                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                     >
                                {% else %}
                                <img src="{% static "deps/images/baseavatar.jpg" %}"
                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                     style="max-width: 150px;">
                                {% endif %}
                            </div>

                            <div style="flex-direction: column;" class="details">
                                <input type="file"  id="id_image"
                                       name="image"
                                       accept="image/*">
                                {% if form.image.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                {% endif %}
                                <div class="mb-3 flex-row">
                                    <label for="id_first_name" class="form-label">Имя</label>
                                    <input type="text" class="form-control"
                                           id="id_first_name"
                                           name="first_name"
                                           placeholder="Введите ваше имя"
                                           value="{{form.first_name.value}}"
                                           required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                                </div>
                                <div  class="mb-3 flex-row">
                                    <label for="id_last_name" class="form-label">Фамилия</label>
                                    <input type="text"
                                           class="form-control"
                                           id="id_last_name"
                                           name="last_name"
                                           placeholder="Введите вашу фамилию"
                                           value="{{form.last_name.value}}"
                                           required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                                </div>
                                <div  class="mb-3 flex-row">
                                    <label for="id_username" class="form-label">Имя пользователя</label>
                                    <input type="text"
                                           class="form-control"
                                           id="id_username"
                                           name="username"
                                           placeholder="Введите ваше имя пользователя"
                                           value="{{form.username.value}}" required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="mb-3 flex-row">
                                    <label for="id_email" class="form-label">Email</label>
                                    <input type="email"
                                           class="form-control"
                                           id="id_email"
                                           name="email"
                                           placeholder="Введите ваш email *youremail@example.com"
                                           value="{{ form.email.value }}" required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="mb-3 flex-row">
                                    <label for="id_phone" class="form-label">Телефон</label>
                                    <input type="text"
                                           class="form-control"
                                           id="id_phone"
                                           value="{{ form.phone.value }}"
                                           name="phone"
                                           placeholder="Введите ваш телефон" required>
                                    {% if form.phone.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.phone.errors}}</div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="order">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            <div class="col-md-7">
                <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="title-basket prof">Корзина</h3>
                    <div class="container" id="basket-items-container">
                        <!-- Разметка корзины -->
                        {% include "baskets/includes/included_basket.html" %}
                    </div>
                    {% if user_baskets and not orders %}
                    <a class="order" href="{% url "orders:create_order" %}">
                        Оформить заказ
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="container mt-5">
                <div class="col-md-12">
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="title-basket prof">Мои заказы</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                {% for order in orders %}
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading{{ order.id }}">
                                        <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                            Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{order.requires_delivery}}</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Блюдо</th>
                                                        <th>Количество</th>
                                                        <th>Цена</th>
                                                        <th>Общая стоимость</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for item in order.orderitem_set.all %}
                                                    <tr>
                                                        <td>{{ item.dish.name }}</td>
                                                        <td>{{ item.quantity }}</td>
                                                        <td>{{ item.price }}</td>
                                                        <td>{{ item.dishes_price }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% comment %}
                        <div class="container">
                        </div>
                        {% endcomment %}
                        <!-- Закончилась разметка заказов -->
                    </div>
                </div>
            </div>
            <!-- Закончилась разметка корзины -->
        </div>
    </div>
    <!-- Оформленные заказы -->
    
</section>

{% endblock body %}