Coffee_shop/coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from coffee_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('menu/', include('goods.urls', namespace='menu')),
    path('user/', include('users.urls', namespace='user')),

    path('__debug__/', include('debug_toolbar.urls')),
    path('basket/', include('baskets.urls', namespace="basket")),
    path('order/', include('orders.urls', namespace="order")),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coffee_shop/coffee_shop/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('main/', views.main_page, name='main_page'),  
    
]

Coffee_shop/coffee_shop/orders/urls.py
from django.urls import path 
from  orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

Coffee_shop/coffee_shop/orders/models.py
from django.db import models

from baskets.models import Dishes
from users.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self) -> int:
        return sum(basket.dish_price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)

        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default="В обработке", verbose_name="Статус заказа")

    class Meta:
        db_table="order"
        verbose_name="Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    dish = models.ForeignKey(to=Dishes, on_delete=models.SET_DEFAULT, null=True, verbose_name="Блюдо", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity=models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    objects = OrderItemQuerySet.as_manager()

    def dishes_price(self):
        return round(self.dish.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

Coffee_shop/coffee_shop/orders/forms.py
from django import forms
import re

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
            ],
        )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
            ],
        )

    def clean_phone(self):
        data = self.cleaned_data['phone']

        # if not data.isdigit():
        #     raise forms.ValidationError("Номер телефона не соответствует формату")
        pattern = re.compile(r'^\+7 \(\d{3}\)-\d{3}-\d{4}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера. Формат: +7 (000)-000-0000")

        return data

Coffee_shop/coffee_shop/orders/views.py
from django.contrib import messages
from django.forms import ValidationError
from django.shortcuts import redirect, render
from baskets.templatetags.baskets_tags import user_baskets
# Create your views here.
from baskets.models import Baskets
from orders.models import Order, OrderItem
from orders.forms import CreateOrderForm
from django.db import transaction
from django.contrib.auth.decorators import login_required
# import logging

# logging.getLogger('django')
@login_required
def create_order(request):
    
    if request.method == "POST":
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    basket_items = Baskets.objects.filter(user=user)

                    if basket_items.exists():
                        order = Order.objects.create(
                            user=user,
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )

                        for basket_item in basket_items:
                            dish=basket_item.dish
                            name=basket_item.dish.name
                            price=basket_item.dish.sell_price()
                            quantity=basket_item.quantity
                    
                            if dish.quantity < quantity:
                                raise ValidationError( f'Недостаточное количество товара {name} на складе. В наличии - {dish.quantity}' )

                            OrderItem.objects.create(
                                    order=order,
                                    dish=dish,
                                    name=name,
                                    price=price,
                                    quantity=quantity,
                            )
                            dish.quantity -= quantity
                            dish.save()
                
                        basket_items.delete()
                        messages.success(request, "Заказ оформлен!")
                        return redirect("users:profile")


            except ValidationError as e:
                error_e=str(e)
                messages.success(request, error_e)
                return redirect('users:users-basket')

    else:
        initial = {
            'first_name' : request.user.first_name,
            'last_name': request.user.last_name,
            'phone' : request.user.phone,
        }
        # logging.debug(f'Имя:{request.user.first_name}  Фамилия:{request.user.last_name} телефон:{request.user.phone}  объект:{request.user}')
        form = CreateOrderForm(initial=initial)
    context={
        'title': 'Home - Оформление заказа',
        'form': form,
    }
    user_baskets(context, request)
    return render(request, "orders/create_order.html", context)

Coffee_shop/coffee_shop/orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<section class="order-main" id="basket-main">
    <div class="container">
        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <div class="container">
                <h3 class="title-basket">Выбранные товары</h3>
                <div class="container" id="basket-items-container">
                    <!-- Разметка корзины -->
                    {% include "baskets/includes/included_basket.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
            <!-- Детали заказа -->
            <div class="container">
                <h3 class="title-basket" style="margin-bottom: 30px;">Детали заказа</h3>
            
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{% url "orders:create_order" %}" method="post">
                                
                                    <div class="details">
                                
                                        {% csrf_token %}
                                        <div  class="mb-3 flex-row">
                                            <label for="id_first_name" class="form-label">Имя:</label>
                                            <input type="text" class="form-control" id="id_first_name"
                                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                                name="first_name" required>
                                            {% if form.first_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div  class="mb-3 flex-row">
                                            <label for="id_last_name" class="form-label">Фамилия:</label>
                                            <input type="text" class="form-control" id="id_last_name"
                                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                                name="last_name" required>
                                            {% if form.last_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div  class="mb-3 flex-row">
                                            <label for="id_phone" class="form-label">Номер телефона:</label>
                                            <input type="text" class="form-control" id="id_phone"
                                                value="{% if form.phone.value %}{{ form.phone.value }}{% endif %}"
                                                name="phone" placeholder="В формате: +7 (000)-000-0000" required>
                                            {% if form.phone.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.phone.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="mb-3">
                                            <label for="delivery" class="form-label">Способ доставки:</label>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="requires_delivery"
                                                    id="id_requires_delivery" value="1" checked>
                                                <label class="form-check-label" for="id_requires_delivery">Нужна доставка</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="requires_delivery"
                                                    id="id_requires_delivery" value="0">
                                                <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                                            </div>
                                        </div>


                                        <div  class="mb-3 flex-row" id="deliveryAddressField">
                                            <label for="id_delivery_address" class="form-label">Адрес доставки:</label>
                                            <input class="form-control" id="id_delivery_address" name="delivery_address"
                                                rows="1">{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}</input>
                                            {% if form.delivery_address.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                            {% endif %}
                                        </div>

                                        
                                        <div class="mb-3">
                                            <label class="form-label">Способ оплаты:</label>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="payment_on_get"
                                                    id="id_payment_on_get" value="0" checked>
                                                <label class="form-check-label" for="id_payment_on_get">Оплата картой</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="payment_on_get"
                                                    id="id_payment_on_get" value="1">
                                                <label class="form-check-label" for="id_payment_on_get">Наличными/картой при плучении</label>
                                            </div>
                                        </div>
                                    </div>
                                <button type="submit" class="order">Оформить заказ</button>
                            </form>
                        </div>
                    </div>
                
            
            </div>
        </div>
    </div>
</section>

{% endblock body %}

{% block extra_scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const input = document.getElementById('id_delivery_address');

        input.addEventListener('input', function() {
            this.style.width = 'auto';
            this.style.width = (this.scrollWidth + 10) + 'px'; // Добавляем небольшой отступ
        });

        // Вызываем событие input для первоначальной настройки ширины поля
        input.dispatchEvent(new Event('input'));
    });

</script>
{% endblock %}

Coffee_shop/coffee_shop/orders/templates/orders/order_dish.html
{% comment %} {% extends "base.html" %} {% load static %} {% block content %}
<div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
	<div class="container">
		<h3 class="text-center mb-4">Выбранные товары</h3>
		<div class="container" id="cart-items-container">
			<!-- Разметка корзины -->
			<div class="card mb-3 text-bg-light shadow-lg">
				<div class="card-header">
					<h5 class="card-title">Товар</h5>
				</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">
						<div class="row text-center">
							<div class="col p-0">
								<div class="input-group">
									<span class="input-group-btn">
										<button
											type="button"
											class="btn btn-dark btn-sm decrement"
											data-cart-id=""
											data-cart-change-url=""
										>
											-
										</button>
									</span>
									<input
										type="text"
										class="form-control number"
										value="1"
										readonly
									/>
									<span class="input-group-btn">
										<button
											type="button"
											class="btn btn-dark btn-sm increment"
											data-cart-id=""
											data-cart-change-url=""
										>
											+
										</button>
									</span>
								</div>
							</div>
							<div class="col p-0">
								<p>x 100.00 =</p>
							</div>
							<div class="col p-0"><strong>100.00 $</strong></div>
							<div class="col p-0">
								<a href="#" class="remove-from-cart" data-cart-id="">
									<img
										class="mx-1"
										src="../deps/icons/trash3-fill.svg"
										alt="Catalog Icon"
										width="16"
										height="16"
									/>
								</a>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="card mb-3 shadow-lg">
				<div class="card-footer">
					<p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
					<h4 class="float-left"><strong>100.00 $</strong></h4>
				</div>
			</div>
			<!-- Закончилась разметка корзины -->
		</div>
	</div>
	<!-- Детали заказа -->
	<div class="container">
		<h3 class="text-center">Детали заказа</h3>
		<div class="card mb-3">
			<div class="card-body">
				<form>
					<div class="row">
						<div class="col-md-6 mb-3">
							<label for="id_first_name" class="form-label">Имя*:</label>
							<input
								type="text"
								class="form-control"
								id="id_first_name"
								name="first_name"
								required
							/>
						</div>
						<div class="col-md-6 mb-3">
							<label for="id_last_name" class="form-label">Фамилия*:</label>
							<input
								type="text"
								class="form-control"
								id="id_last_name"
								name="last_name"
								required
							/>
						</div>
						<div class="col-md-6 mb-3">
							<label for="id_phone_number" class="form-label"
								>Номер телефона*:</label
							>
							<input
								type="text"
								class="form-control"
								id="id_phone_number"
								name="phone_number"
								placeholder="В формате: XXX-XXX-XX-XX"
								required
							/>
						</div>
						<div class="col-md-12 mb-3">
							<label for="delivery" class="form-label">Способ доставки: </label>
							<div class="form-check form-check-inline">
								<input
									class="form-check-input"
									type="radio"
									name="requires_delivery"
									id="id_requires_delivery"
									value="1"
									checked
								/>
								<label class="form-check-label" for="id_requires_delivery"
									>Нужна доставка</label
								>
							</div>
							<div class="form-check form-check-inline">
								<input
									class="form-check-input"
									type="radio"
									name="requires_delivery"
									id="id_requires_delivery"
									value="0"
								/>
								<label class="form-check-label" for="id_requires_delivery"
									>Самовывоз</label
								>
							</div>
						</div>
						<div class="mb-3" id="deliveryAddressField">
							<label for="id_delivery_address" class="form-label"
								>Адрес доставки*:</label
							>
							<textarea
								class="form-control"
								id="id_delivery_address"
								name="delivery_address"
								rows="2"
							></textarea>
						</div>
						<div class="col-md-12 mb-3">
							<label class="form-label">Способ оплаты: </label>
							<div class="form-check form-check-inline">
								<input
									class="form-check-input"
									type="radio"
									name="payment_on_get"
									id="id_payment_on_get"
									value="0"
									checked
								/>
								<label class="form-check-label" for="id_payment_on_get"
									>Оплата картой</label
								>
							</div>
							<div class="form-check form-check-inline">
								<input
									class="form-check-input"
									type="radio"
									name="payment_on_get"
									id="id_payment_on_get"
									value="1"
								/>
								<label class="form-check-label" for="id_payment_on_get"
									>Наличными/картой при плучении</label
								>
							</div>
						</div>
					</div>
					<button type="submit" class="btn btn-dark">Оформить заказ</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %} {% endcomment %}