Coffee_shop/coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from coffee_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('menu/', include('goods.urls', namespace='menu')),
    path('user/', include('users.urls', namespace='user')),

    path('__debug__/', include('debug_toolbar.urls')),
    path('basket/', include('baskets.urls', namespace="basket")),
    path('order/', include('orders.urls', namespace="order")),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coffee_shop/coffee_shop/goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    # path('', views.catalog, name='index'),
    path('<slug:category_slug>/', views.catalog, name='catalog'),
    path('search/', views.catalog, name='search'),
    # path('<slug:category_slug>/<int:page>/', views.catalog, name='index'),
    path('dish/<slug:dish_slug>/', views.dish, name='dish'),

    # path('menu/', views.menu, name='menu'),
    # path('', views.menu, name='menu'),
    # path('<slug:category_slug>/', views.menu, name='index'),
    # path('search/', views.menu, name='search'),
]

Coffee_shop/coffee_shop/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('main/', views.main_page, name='main_page'),  
    
]

Coffee_shop/coffee_shop/main/models.py
from django.db import models

# Create your models here.

Coffee_shop/coffee_shop/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from baskets.templatetags.baskets_tags import user_baskets

from goods.models import Categories


# Create your views here.


def index(request):
    context = {
        'title': 'Home - Главная',
        'content': "Магазин мебели HOME",
    }

    user_baskets(context, request)
    return render(request, 'main/index.html', context)



def about(request):
    context = {
        'title': 'Home - О нас',
        'content': "О нас",
        'text_on_page': "Текст о том почему этот магазин такой классный, и какой хороший товар."
    }

    user_baskets(context, request)
    return render(request, 'main/about.html', context)





def main_page(request):
    return render(request, 'main/main.html')

Coffee_shop/coffee_shop/main/templates/main/about.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock %}
{% load baskets_tags %}
{% block modal_basket %}
{% include "includes/basket_button.html"%}
{% endblock %}

{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow rounded">
        <h2 class="m-2"><strong>{{ content }}</strong></h2>
        <p class="m-2">{{ text_on_page }}</p>
    </div>
{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home 2023</p>
    </div>
</footer>
{% endblock %}

Coffee_shop/coffee_shop/main/templates/main/base.html
{% load static %}

{% load goods_tags  %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}{% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="users/login.html">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="users/profile.html">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>



                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>





                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">


                        {% tag_categories as categories %}
                        {% for category in categories  %}
                        <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{category.name}}</a></li>
                        {% endfor %}



                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </section>

    {% block footer %}{% endblock %}

    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

Coffee_shop/coffee_shop/main/templates/main/index.html
{% extends "base.html" %}
{% load static %}




{% block body %}

<main id="main" class="main">
    <section class="welcome ">
      <div class="container">
      
        <h2 class="welcome__heading  animate__animated animate__fadeInUp">Cafe Rofflan</h2>

        <div class="welcome__links">
          <a href="{% url "menu:catalog" category_slug="all" %}" class="link-primary animate__animated animate__fadeInLeft">Меню</a>
          <a href="#about-us" class="link animate__animated animate__fadeInRight ">О нас</a>
        </div>
      </div>
    </section>
   
    <section class="about common-section ">
      <div class="container">
        
        <div class="title-wrapper">
          <h3 class="title">Почему именно мы?</h3>
          <!-- <p class="subtitle">This is some text inside of a div block.</p> -->
        </div>

        <div class="cards-wrapper">
          <div class="card wow animate__animated animate__fadeInLeft">
            <img src="{% static 'main/img/icon.png' %} " alt="icon">
            <h4>Качество</h4>
            <p>Мы используем только лучшие ингредиенты, чтобы каждый наш десерт стал настоящим шедевром.</p>
          </div>
          <div class="card wow animate__animated animate__fadeInUp">
            <img src="{% static 'main/img/love.png' %} " alt="icon">
            <h4>Атмосфера</h4>
            <p> У нас царит особая атмосфера уюта и комфорта, где каждый гость чувствует себя как дома, окруженный теплом и заботой.</p>
          </div>
          <div class="card wow animate__animated animate__fadeInRight">
            <img src="{% static 'main/img/delishes.png' %} " alt="icon">
            <h4>Вкус</h4>
            <p>У нас вы откроете для себя идеальное сочетание ингредиентов, создающее незабываемые вкусовые ощущения.</p>
          </div>
        </div>
      </div>
      <div id="about-us"></div>
    </section>
    
    <section   class="services common-section common-section--dark ">
      <div class="container">
        <div class="title-wrapper">
          <h3  class="title  dish">Изделия</h3>
          <p class="subtitle">В Rofflan каждое блюдо создается нашими опытными кондитерами и поварами. 
            Они творят великолепие с любовью и профессионализмом, чтобы каждое изделие стало настоящим произведением искусства.</p>
        </div>

        <div class="cards-wrapper">
          <div class="card min">
            <img class="wow animate__animated animate__fadeInLeft" style="margin-bottom: 20px;" src="{% static 'main/img/вензель.jpg' %} " alt="img">
            <img class="wow animate__animated animate__fadeInUp" src="{% static 'main/img/2.jpg' %}" alt="img">
          </div>
          <div class="card">
            <img class="wow animate__animated animate__fadeInRight" style="height: 530px;" src="{% static 'main/img/1.jpg' %}" alt="img">
          </div>
        </div>
        
      </div>
      <div id="address"></div>
    </section>

    <section class="tab-section common-section ">
      <div class="container">
        <div class="title-wrapper">
          <h3  class="title ">Где нас найти?</h3>
        </div>

        <div class="tabs">
          <!-- <div class="tabs__nav">
            <button class="active" type="button">Tab Button 1</button>
            <button type="button">Tab Button 2</button>
            <button type="button">Tab Button 3</button>
          </div> -->

          <div class="tabs__item">
          
            
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1999.1573370109097!2d30.365641578086738!3d59.929531374910624!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x469631bbeb6ed1cf%3A0x231ce6ca8cbd8309!2z0J3QtdCy0YHQutC40Lkg0L_RgC4sIDEwNSwg0KHQsNC90LrRgi3Qn9C10YLQtdGA0LHRg9GA0LMsINCg0L7RgdGB0LjRjywgMTkxMDM2!5e0!3m2!1sru!2sfr!4v1719418915655!5m2!1sru!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <div class="text-map wow animate__animated animate__flipInY">

              <div class="tabs__desc">
                <p>Наше кафе находится в самом центре Санкт-Петербурга по адресу:</p>
                <p class="address">Невский пр., 105, Санкт-Петербург, Россия, 191036.</p>

                  <p>Мы работаем ежедневно  </p>
                  <div class="time">с 10:00 до 22:00.</div>

            </div>

          </div>
        </div>
      </div>
    </section>
  </main>

{% endblock body %}

Coffee_shop/coffee_shop/main/templates/main/main.html
{% extends "base.html" %}
{% load static %}




{% block body %}

<main id="main" class="main">
    <section class="welcome ">
      <div class="container">
        <h2 class="welcome__heading  animate__animated animate__fadeInUp">Cafe Rofflan</h2>

        <div class="welcome__links">
          <a href="{% url "menu:catalog" category_slug="all" %}" class="link-primary animate__animated animate__fadeInLeft">Меню</a>
          <a href="#about-us" class="link animate__animated animate__fadeInRight ">О нас</a>
        </div>
      </div>
    </section>

    <section class="about common-section ">
      <div class="container">
        <div class="title-wrapper">
          <h3 class="title">Почему именно мы?</h3>
          <!-- <p class="subtitle">This is some text inside of a div block.</p> -->
        </div>

        <div class="cards-wrapper">
          <div class="card wow animate__animated animate__fadeInLeft">
            <img src="{% static 'main/img/icon.png' %} " alt="icon">
            <h4>Качество</h4>
            <p>Мы используем только лучшие ингредиенты, чтобы каждый наш десерт стал настоящим шедевром.</p>
          </div>
          <div class="card wow animate__animated animate__fadeInUp">
            <img src="{% static 'main/img/love.png' %} " alt="icon">
            <h4>Атмосфера</h4>
            <p> У нас царит особая атмосфера уюта и комфорта, где каждый гость чувствует себя как дома, окруженный теплом и заботой.</p>
          </div>
          <div class="card wow animate__animated animate__fadeInRight">
            <img src="{% static 'main/img/delishes.png' %} " alt="icon">
            <h4>Вкус</h4>
            <p>У нас вы откроете для себя идеальное сочетание ингредиентов, создающее незабываемые вкусовые ощущения.</p>
          </div>
        </div>
      </div>
      <div id="about-us"></div>
    </section>
    
    <section   class="services common-section common-section--dark ">
      <div class="container">
        <div class="title-wrapper">
          <h3  class="title  dish">Изделия</h3>
          <p class="subtitle">В Rofflan каждое блюдо создается нашими опытными кондитерами и поварами. 
            Они творят великолепие с любовью и профессионализмом, чтобы каждое изделие стало настоящим произведением искусства.</p>
        </div>

        <div class="cards-wrapper">
          <div class="card min">
            <img class="wow animate__animated animate__fadeInLeft" style="margin-bottom: 20px;" src="{% static 'main/img/вензель.jpg' %} " alt="img">
            <img class="wow animate__animated animate__fadeInUp" src="{% static 'main/img/2.jpg' %}" alt="img">
          </div>
          <div class="card">
            <img class="wow animate__animated animate__fadeInRight" style="height: 530px;" src="{% static 'main/img/1.jpg' %}" alt="img">
          </div>
        </div>
        
      </div>
      <div id="address"></div>
    </section>

    <section class="tab-section common-section ">
      <div class="container">
        <div class="title-wrapper">
          <h3  class="title ">Где нас найти?</h3>
        </div>

        <div class="tabs">
          <!-- <div class="tabs__nav">
            <button class="active" type="button">Tab Button 1</button>
            <button type="button">Tab Button 2</button>
            <button type="button">Tab Button 3</button>
          </div> -->

          <div class="tabs__item">
          
            
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1999.1573370109097!2d30.365641578086738!3d59.929531374910624!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x469631bbeb6ed1cf%3A0x231ce6ca8cbd8309!2z0J3QtdCy0YHQutC40Lkg0L_RgC4sIDEwNSwg0KHQsNC90LrRgi3Qn9C10YLQtdGA0LHRg9GA0LMsINCg0L7RgdGB0LjRjywgMTkxMDM2!5e0!3m2!1sru!2sfr!4v1719418915655!5m2!1sru!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <div class="text-map wow animate__animated animate__flipInY">

              <div class="tabs__desc">
                <p>Наше кафе находится в самом центре Санкт-Петербурга по адресу:</p>
                <p class="address">Невский пр., 105, Санкт-Петербург, Россия, 191036.</p>

                  <p>Мы работаем ежедневно  </p>
                  <div class="time">с 10:00 до 22:00.</div>

            </div>

          </div>
        </div>
      </div>
    </section>
  </main>

{% endblock body %}